title: Jen Arriaza # your name (or website title) here
logo: "/images/pfpupdate2.png?raw=true" # your photo (or logo) here
plugins:
  - jemoji
description: > # text below
  <br>
  <b><h2>Hello! I'm Jen :seedling:</b></h2>
  <p>I use data science to solve problems and build data-powered intelligent systems.<br>
  <br>
  <br>
  <a href="https://github.com/zenjen-dev"><img style="vertical-align:middle" src="https://cdn.iconscout.com/icon/free/png-256/github-113-438180.png" height="22" width="22" class="center"/> Github</a><br>  
  <a href="https://www.linkedin.com/in/jarriaza/"><img src="https://cdn-icons-png.flaticon.com/512/174/174857.png" height="20" width="20" class="center"/> LinkedIn</a><br>  
  <a href="https://twitter.com/jen_arriaza/"><img src="https://cdn-icons-png.flaticon.com/512/2190/2190356.png" height="20" width="20" class="center"/> Twitter</a><br> 
  <a href="https://www.instagram.com/zenjen.dev/"><img src="https://cdn-icons-png.flaticon.com/512/174/174855.png" height="20" width="20" class="center"/> Instagram</a><br> 

  &nbsp;
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
